"""initial_schema

Revision ID: 194380b7d429
Revises: 
Create Date: 2026-07-28 16:11:37.873572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194380b7d429'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.String(length=10), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmacia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_cuit', sa.String(length=11), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cuit')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula_nacional', sa.String(length=20), nullable=True),
    sa.Column('matricula_provincial', sa.String(length=20), nullable=True),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medico_matricula_nacional'), ['matricula_nacional'], unique=False)
        batch_op.create_index(batch_op.f('ix_medico_matricula_provincial'), ['matricula_provincial'], unique=False)

    op.create_table('monodroga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('obra_social',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=False),
    sa.Column('cuit', sa.String(length=11), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('cuit')
    )
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permiso_codigo'), ['codigo'], unique=True)

    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rol_nombre'), ['nombre'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cobertura_porcentaje_defecto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['obra_social_id'], ['obra_social.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('afiliado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('numero_afiliado', sa.String(length=30), nullable=False),
    sa.Column('numero_documento', sa.String(length=15), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['obra_social_id'], ['obra_social.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('afiliado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_afiliado_numero_afiliado'), ['numero_afiliado'], unique=False)

    op.create_table('receta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_receta', sa.String(length=30), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('obra_social_id', sa.Integer(), nullable=False),
    sa.Column('farmacia_id', sa.Integer(), nullable=False),
    sa.Column('afiliado_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prescripcion', sa.Date(), nullable=False),
    sa.Column('fecha_dispensa', sa.Date(), nullable=False),
    sa.Column('total_pvp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cobertura_os', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliado.id'], ),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacia.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['obra_social_id'], ['obra_social.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receta_numero_receta'), ['numero_receta'], unique=False)

    op.create_table('receta_detalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('monodroga_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('pvp_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('porcentaje_cobertura', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_cobertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['monodroga_id'], ['monodroga.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receta_detalle')
    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receta_numero_receta'))

    op.drop_table('receta')
    with op.batch_alter_table('afiliado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_afiliado_numero_afiliado'))

    op.drop_table('afiliado')
    op.drop_table('usuario_rol')
    op.drop_table('rol_permiso')
    op.drop_table('plan')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rol_nombre'))

    op.drop_table('rol')
    with op.batch_alter_table('permiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permiso_codigo'))

    op.drop_table('permiso')
    op.drop_table('periodo')
    op.drop_table('obra_social')
    op.drop_table('monodroga')
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medico_matricula_provincial'))
        batch_op.drop_index(batch_op.f('ix_medico_matricula_nacional'))

    op.drop_table('medico')
    op.drop_table('farmacia')
    op.drop_table('auditoria_log')
    # ### end Alembic commands ###
